In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity,euclidean_distances

In [2]:
df=pd.read_csv('Movies_csv.csv')
df.head()

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [3]:
df.shape

(8992, 3)

In [4]:
# how many  unique users
len(df.userId.unique())

4081

In [5]:
# how mamy unique movies
len(df.movie.unique())

10

In [6]:
# how many unique rating have
len(df.rating.unique())

10

In [7]:
# which movie viewed more-----> so we need to find average and analyse based on rating
df.groupby('movie')['rating'].mean().sort_values(ascending=False)[:6]

movie
Toy Story (1995)       3.959323
Heat (1995)            3.836508
GoldenEye (1995)       3.427003
Sabrina (1995)         3.381429
Tom and Huck (1995)    3.352564
Jumanji (1995)         3.268398
Name: rating, dtype: float64

# cosine similarity

## 1) item-based

In [8]:
# we can see the rating values having decimal. for doing this we need whole number format so we need to convert to pivot_table
# here item is movie. we need set item which means index='movie',columns='user_id',value=rating
df1=df.pivot_table(index='movie',columns='userId',values='rating')
df1.fillna(0,axis=1,inplace=True)
df1.head()

userId,1,2,3,4,5,6,7,8,10,11,...,7105,7107,7108,7110,7113,7115,7116,7117,7119,7120
movie,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
GoldenEye (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Heat (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Jumanji (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0

In [9]:
df1.index

Index(['Father of the Bride Part II (1995)', 'GoldenEye (1995)',
       'Grumpier Old Men (1995)', 'Heat (1995)', 'Jumanji (1995)',
       'Sabrina (1995)', 'Sudden Death (1995)', 'Tom and Huck (1995)',
       'Toy Story (1995)', 'Waiting to Exhale (1995)'],
      dtype='object', name='movie')

In [10]:
# cosine similarity
cos_sim=cosine_similarity(df1)
cos_sim

array([[1.        , 0.21599275, 0.45566216, 0.24736744, 0.27980393,
        0.39574604, 0.22645759, 0.16293622, 0.30863759, 0.16378738],
       [0.21599275, 1.        , 0.21819777, 0.39773907, 0.40226034,
        0.22145469, 0.1552551 , 0.11972423, 0.38348625, 0.12844824],
       [0.45566216, 0.21819777, 1.        , 0.2901502 , 0.24471005,
        0.39017783, 0.25538652, 0.14395914, 0.31691062, 0.1564475 ],
       [0.24736744, 0.39773907, 0.2901502 , 1.        , 0.2800876 ,
        0.26207226, 0.25562862, 0.06285821, 0.40011642, 0.12402064],
       [0.27980393, 0.40226034, 0.24471005, 0.2800876 , 1.        ,
        0.24667163, 0.14328579, 0.19637377, 0.40998238, 0.14767896],
       [0.39574604, 0.22145469, 0.39017783, 0.26207226, 0.24667163,
        1.        , 0.20155614, 0.16464129, 0.31043392, 0.1894145 ],
       [0.22645759, 0.1552551 , 0.25538652, 0.25562862, 0.14328579,
        0.20155614, 1.        , 0.09721338, 0.16679265, 0.15179972],
       [0.16293622, 0.11972423, 0.14395914, 0.06285821, 0.19637377,
        0.16464129, 0.09721338, 1.        , 0.09552068, 0.14872289],
       [0.30863759, 0.38348625, 0.31691062, 0.40011642, 0.40998238,
        0.31043392, 0.16679265, 0.09552068, 1.        , 0.13852446],
       [0.16378738, 0.12844824, 0.1564475 , 0.12402064, 0.14767896,
        0.1894145 , 0.15179972, 0.14872289, 0.13852446, 1.        ]])

In [62]:
def recommended_movie(similar_movie):
    if similar_movie in df1.index:
        index = np.where(similar_movie == df1.index)[0][0]
        similar = sorted(list(enumerate(cos_sim[index])),reverse=True,key=lambda x: x[1])[1:6]
        print("Recommended movie of ", similar_movie)
        for i in similar:
            print(df1.index[i[0]])
    else:
        print("Movie is not in the list")

In [63]:
recommended_movie('titanic')

Movie is not in the list

## 2) user-based

In [13]:
df2=df.pivot_table(index='userId',columns='movie',values='rating')
df2.fillna(0,axis=1,inplace=True)
df2.head()

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
4,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0

In [24]:
# calculate the cosine_similarity and convert into Dataframe and stored in df3 
df3=pd.DataFrame(cosine_similarity(df2),index=df.userId.unique(),columns=df.userId.unique())
df3[df3[3]>0.8][3].sort_values(ascending=False)[1:6]

11     1.0
189    1.0
199    1.0
209    1.0
221    1.0
Name: 3, dtype: float64

In [26]:
df[(df.userId==3)|(df.userId==221)]

    userId             movie  rating
0        3  Toy Story (1995)     4.0
76     221  Toy Story (1995)     4.0

# 2)Eucledian distance

## item_based

In [27]:
df1=df.pivot_table(index='movie',columns='userId',values='rating')
df1.fillna(0,axis=1,inplace=True)
df1.head()

userId,1,2,3,4,5,6,7,8,10,11,...,7105,7107,7108,7110,7113,7115,7116,7117,7119,7120
movie,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
GoldenEye (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Heat (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Jumanji (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0

In [54]:
euclidean_distance=euclidean_distances(df1)

In [55]:
def recommended_movie(similar_movie):
    if similar_movie in df1.index:
        index = np.where(similar_movie == df1.index)[0][0]
        similar = sorted(list(enumerate(euclidean_distance[index])),reverse=False,key=lambda x: x[1])[1:6]
        print("Recommended movie of ", similar_movie)
        print("*"*30)
        for i in similar:
            print(df1.index[i[0]])
    else:
        print("Movie is not in the list")

In [56]:
recommended_movie('Jumanji (1995)')

Recommended movie of  Jumanji (1995)
******************************
Tom and Huck (1995)
Waiting to Exhale (1995)
Sudden Death (1995)
Father of the Bride Part II (1995)
Grumpier Old Men (1995)

## user_based

In [57]:
df2=df.pivot_table(index='userId',columns='movie',values='rating')
df2.fillna(0,axis=1,inplace=True)
df2.head()

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
4,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0

In [59]:
df3=pd.DataFrame(euclidean_distance(df2),index=df.userId.unique(),columns=df.userId.unique())
df3[df3[10]<1][10].sort_values()[1:6]

TypeError: 'numpy.ndarray' object is not callable

In [60]:
df[(df.userId==10)|(df.userId==2706)]

      userId             movie  rating
3         10  Toy Story (1995)     4.0
3005    2706    Jumanji (1995)     4.0
8039    2706  GoldenEye (1995)     4.0

# person correlation

## item

In [61]:
df1=df.pivot_table(index='movie',columns='userId',values='rating')
df1.fillna(0,axis=1,inplace=True)
df1.head()

userId,1,2,3,4,5,6,7,8,10,11,...,7105,7107,7108,7110,7113,7115,7116,7117,7119,7120
movie,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
GoldenEye (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Heat (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Jumanji (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0