In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import f_oneway
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import LabelEncoder,StandardScaler
 
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet,LogisticRegression
from sklearn.metrics import r2_score,classification_report

# 1) LINEAR REGRESIION

In [2]:
df=pd.read_csv('studyhours.csv')
df.head()

   Study_Hours  Attendance  Practice_Hours  Previous_Score  Sleep_Hours  Final_Score
0            2          65               1              45            6           48
1            3          70               2              50            7           53
2            4          72               2              52            6           57
3            5          75               3              55            7           61
4            6          78               3              60            8           65

In [3]:
target=df[['Final_Score']]
features=df.drop(columns='Final_Score')

In [4]:
# splitting data
x_train,x_test,y_train,y_test=train_test_split(target,features,train_size=0.7,random_state=10)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(14, 1)
(6, 1)
(14, 5)
(6, 5)

In [5]:
# model selection
lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)

LinearRegression()

In [6]:
# training validation
y_pred=lin_reg.predict(x_train)
r2_score(y_train,y_pred)

0.8928306837970196

In [7]:
# testing validation
y_pred1=lin_reg.predict(x_test)
r2_score(y_test,y_pred1)

0.8454000261344072

In [8]:
# model selection 
lasso=Lasso()
lasso.fit(x_train,y_train)

Lasso()

In [9]:
# training validation
y_pred=lasso.predict(x_train)
r2_score(y_train,y_pred)

0.8905568320218163

In [10]:
# testing validation
y_pred1=lasso.predict(x_test)
r2_score(y_test,y_pred1)

0.8638712845001241

In [11]:
# model selection 
elastic=ElasticNet()
elastic.fit(x_train,y_train)

ElasticNet()

In [12]:
# training validation 
y_pred=elastic.predict(x_train)
r2_score(y_train,y_pred)

0.8921483332594023

In [13]:
# testing validation
y_pred1=elastic.predict(x_test)
r2_score(y_test,y_pred1)

0.8571513610192643

In [14]:
# model selection 
ridge=Ridge()
ridge.fit(x_train,y_train)

Ridge()

In [15]:
# training validation
y_pred=ridge.predict(x_train)
r2_score(y_train,y_pred)

0.892830467229324

In [16]:
# testing validation
y_pred1=ridge.predict(x_test)
r2_score(y_test,y_pred1)

0.8455683132568466

# 2) KNN

In [17]:
df=pd.read_csv('knndataset.csv')
df.head()

   Age  Study_Hours  Attendance  Previous_Score  Practice_Hours Result
0   18            2          60              40               1   Fail
1   19            3          65              45               1   Fail
2   20            4          68              48               2   Fail
3   21            5          72              52               2   Fail
4   22            6          75              55               3   Pass

In [18]:
le=LabelEncoder()
df['Result']=le.fit_transform(df['Result'])

In [19]:
target=df[['Result']]
features=df.drop(columns='Result')

In [20]:
x_train,x_test,y_train,y_test=train_test_split(target,features,train_size=0.7,random_state=10)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(14, 1)
(6, 1)
(14, 5)
(6, 5)

In [21]:
knn_classi=KNeighborsClassifier(n_neighbors=3)
knn_classi.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [22]:
y_pred=knn_classi.predict(x_train)
r2_score(y_train,y_pred)

0.6078729475687464

In [23]:
y_pred1=knn_classi.predict(x_test)
r2_score(y_test,y_pred1)

-0.08662584968386369

# 3) LOGISTIC REGRESSION

In [24]:
df=pd.read_csv('knndataset.csv')
df.head()

   Age  Study_Hours  Attendance  Previous_Score  Practice_Hours Result
0   18            2          60              40               1   Fail
1   19            3          65              45               1   Fail
2   20            4          68              48               2   Fail
3   21            5          72              52               2   Fail
4   22            6          75              55               3   Pass

In [25]:
le=LabelEncoder()
df['Result']=le.fit_transform(df['Result'])

In [47]:
target=df[['Result']]
features=df.drop(columns=['Result'])

In [48]:
x_train,x_test,y_train,y_test=train_test_split(features,target,train_size=0.7,random_state=10)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(14, 5)
(6, 5)
(14, 1)
(6, 1)

In [49]:
log_reg=LogisticRegression()
log_reg.fit(x_train,y_train)

C:\ProgramData\anaconda8\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [51]:
y_pred=log_reg.predict(x_train)
classification_report(y_train,y_pred)
r2_score(y_train,y_pred)

1.0

In [53]:
y_pred1=log_reg.predict(x_test)
classification_report(y_test,y_pred1)
r2_score(y_test,y_pred1)

1.0