In [1]:
import pandas as pd

# 1) CREATION OF DATAFRAME

# create a dataframe using dictionaries

In [2]:
data={'Name':['Abhi','Akku','Appu','Kuttan'],
      'Age':[22,18,23,23],
      'Salary':[10000,2000,12000,18000]}
df=pd.DataFrame(data)
df

     Name  Age  Salary
0    Abhi   22   10000
1    Akku   18    2000
2    Appu   23   12000
3  Kuttan   23   18000

# create a dataframe using list.

In [3]:
data1= [
    ['Abhi', 25, 30000],
    ['Rahul', 24, 35000],
    ['Anu', 23, 28000]
]

In [4]:
df2=pd.DataFrame(data1,columns=['Name','Age','Salary'])
df2

    Name  Age  Salary
0   Abhi   25   30000
1  Rahul   24   35000
2    Anu   23   28000

In [5]:
# Create a Pandas DataFrame using a list of dictionaries with the following data:
# | Name  | Age | City      | Salary |
# | ----- | --  | --------- | -----: |
# | Abhi  |  22 | Kannur    |  25000 |
# | Rahul |  24 | Kochi     |  35000 |
# | Anu   |  23 | Bangalore |  40000 |
# | Akhil |  26 | Chennai   |  45000 |

In [6]:
list1=[['Abhi',22,'Kannur',25000],
     ['Rahul',24,'Kochi',35000],
     ['Anu',23,'Bangalore',40000],
     ['Akhil',26,'Chennai',45000]]
df3=pd.DataFrame(list1,columns=['Name','Age','Location','Salary'])
df3

    Name  Age   Location  Salary
0   Abhi   22     Kannur   25000
1  Rahul   24      Kochi   35000
2    Anu   23  Bangalore   40000
3  Akhil   26    Chennai   45000

In [7]:
# Create a DataFrame using a list of lists:

# Product 	Price	Quantity
# Laptop	50000	2
# Mouse	    1000	5
# Keyboard	2000	3
# Monitor	15000	4
list2=[['Laptop',50000,2],
      ['Mouse',1000,5],
      ['Keyboard',2000,3],
      ['Monitor',15000,4]]
df4=pd.DataFrame(list2,columns=['Product','Price','Quantity'])
df4

    Product  Price  Quantity
0    Laptop  50000         2
1     Mouse   1000         5
2  Keyboard   2000         3
3   Monitor  15000         4

# 2)Reading & Inspecting Data

In [8]:
# Read the employees.csv
df5=pd.read_csv('employees.csv')
df5

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
7,108,Priya,25,Marketing,37000,Bangalore,1,76
8,109,Nikhil,38,Finance,72000,Chennai,10,90
9,110,Fathima,27,Sales,48000,Kochi,3,84
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
12,113,Rohan,23,Marketing,33000,Kochi,1,75
13,114,Asha,29,HR,46000,Chennai,4,86
14,115,Sanjay,36,Sales,65000,Bangalore,8,93

In [9]:
# head()--> used to get first 5 rows.
df5.head()

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
4,105,Vishnu,35,Sales,62000,Bangalore,8,88

In [10]:
# head(n)-->used to get first n rows
df5.head(10)

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
7,108,Priya,25,Marketing,37000,Bangalore,1,76
8,109,Nikhil,38,Finance,72000,Chennai,10,90
9,110,Fathima,27,Sales,48000,Kochi,3,84

In [11]:
# tail()--> used to get last 5 rows
df5.tail()

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
12,113,Rohan,23,Marketing,33000,Kochi,1,75
13,114,Asha,29,HR,46000,Chennai,4,86
14,115,Sanjay,36,Sales,65000,Bangalore,8,93

In [12]:
# tail(n)---> used to get last n rows.
df5.tail(7)

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
8,109,Nikhil,38,Finance,72000,Chennai,10,90
9,110,Fathima,27,Sales,48000,Kochi,3,84
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
12,113,Rohan,23,Marketing,33000,Kochi,1,75
13,114,Asha,29,HR,46000,Chennai,4,86
14,115,Sanjay,36,Sales,65000,Bangalore,8,93

In [13]:
# shape()---> gives number of rows and columns.
df5.shape

(15, 8)

In [14]:
# columns()--> gives column name.
df5.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'Salary', 'City',
       'Experience_Years', 'Performance_Score'],
      dtype='object')

In [15]:
# dtypes---> gives datatypes 
df5.dtypes

Employee_ID           int64
Name                 object
Age                   int64
Department           object
Salary                int64
City                 object
Experience_Years      int64
Performance_Score     int64
dtype: object

In [16]:
# info()---> gives information about the dataframe.
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        15 non-null     int64
 1   Name               15 non-null     object
 2   Age                15 non-null     int64
 3   Department         15 non-null     object
 4   Salary             15 non-null     int64
 5   City               15 non-null     object
 6   Experience_Years   15 non-null     int64
 7   Performance_Score  15 non-null     int64
dtypes: int64(5), object(3)
memory usage: 1.1+ KB

In [17]:
# describe()---> gives statical summary of numerical columns
df5.describe()

,Employee_ID,Age,Salary,Experience_Years,Performance_Score
count,15.000000,15.000000,15.000000,15.000000,15.000000
mean,108.000000,29.800000,51000.000000,4.800000,85.466667
std,4.472136,4.522957,12716.693191,3.051931,6.289068
min,101.000000,23.000000,33000.000000,1.000000,75.000000
25%,104.500000,26.500000,40500.000000,2.500000,80.500000
50%,108.000000,29.000000,48000.000000,4.000000,86.000000
75%,111.500000,33.000000,61000.000000,7.500000,90.500000
max,115.000000,38.000000,72000.000000,10.000000,94.000000

#

# 3) SELECTING DATA

# column wise

# single column based

In [18]:
# Select the Name column.
df5['Name']

0        Arun
1       Meera
2       Rahul
3      Anjali
4      Vishnu
5       Sneha
6     Adithya
7       Priya
8      Nikhil
9     Fathima
10      Kiran
11       Diya
12      Rohan
13       Asha
14     Sanjay
Name: Name, dtype: object

In [19]:
# Select the Salary column.
df5['Salary']

0     35000
1     42000
2     58000
3     39000
4     62000
5     45000
6     55000
7     37000
8     72000
9     48000
10    60000
11    68000
12    33000
13    46000
14    65000
Name: Salary, dtype: int64

In [20]:
# Select the Age column.
df5['Age']

0     24
1     29
2     32
3     26
4     35
5     28
6     31
7     25
8     38
9     27
10    30
11    34
12    23
13    29
14    36
Name: Age, dtype: int64

In [21]:
# Select the City column.
df5['City']

0     Bangalore
1         Kochi
2     Bangalore
3       Chennai
4     Bangalore
5         Kochi
6     Hyderabad
7     Bangalore
8       Chennai
9         Kochi
10    Bangalore
11    Hyderabad
12        Kochi
13      Chennai
14    Bangalore
Name: City, dtype: object

In [22]:
# Select the Department column.
df5['Department']

0            IT
1            HR
2       Finance
3            IT
4         Sales
5            HR
6            IT
7     Marketing
8       Finance
9         Sales
10           IT
11      Finance
12    Marketing
13           HR
14        Sales
Name: Department, dtype: object

# multiple column based

In [23]:
# Select both Name and Salary columns.
df5[['Name','Salary']]

       Name  Salary
0      Arun   35000
1     Meera   42000
2     Rahul   58000
3    Anjali   39000
4    Vishnu   62000
5     Sneha   45000
6   Adithya   55000
7     Priya   37000
8    Nikhil   72000
9   Fathima   48000
10    Kiran   60000
11     Diya   68000
12    Rohan   33000
13     Asha   46000
14   Sanjay   65000

In [24]:
# Select Age and City columns.
df5[['Age','City']]

    Age       City
0    24  Bangalore
1    29      Kochi
2    32  Bangalore
3    26    Chennai
4    35  Bangalore
5    28      Kochi
6    31  Hyderabad
7    25  Bangalore
8    38    Chennai
9    27      Kochi
10   30  Bangalore
11   34  Hyderabad
12   23      Kochi
13   29    Chennai
14   36  Bangalore

In [25]:
# Select these two columns:
# Department
# Salary
df5[['Department','Salary']]

   Department  Salary
0          IT   35000
1          HR   42000
2     Finance   58000
3          IT   39000
4       Sales   62000
5          HR   45000
6          IT   55000
7   Marketing   37000
8     Finance   72000
9       Sales   48000
10         IT   60000
11    Finance   68000
12  Marketing   33000
13         HR   46000
14      Sales   65000

In [26]:
# Select these three columns:
# Name
# Age
# Department
df5[['Name','Age','Department']]

       Name  Age Department
0      Arun   24         IT
1     Meera   29         HR
2     Rahul   32    Finance
3    Anjali   26         IT
4    Vishnu   35      Sales
5     Sneha   28         HR
6   Adithya   31         IT
7     Priya   25  Marketing
8    Nikhil   38    Finance
9   Fathima   27      Sales
10    Kiran   30         IT
11     Diya   34    Finance
12    Rohan   23  Marketing
13     Asha   29         HR
14   Sanjay   36      Sales

In [27]:
# Select these three columns:
# Name
# Salary
# Performance_Score
df5[['Name','Salary','Performance_Score']]

       Name  Salary  Performance_Score
0      Arun   35000                 78
1     Meera   42000                 85
2     Rahul   58000                 91
3    Anjali   39000                 82
4    Vishnu   62000                 88
5     Sneha   45000                 79
6   Adithya   55000                 94
7     Priya   37000                 76
8    Nikhil   72000                 90
9   Fathima   48000                 84
10    Kiran   60000                 92
11     Diya   68000                 89
12    Rohan   33000                 75
13     Asha   46000                 86
14   Sanjay   65000                 93

In [28]:
#HR wants to see only these columns:
# Name
# Department
# Salary
df5[['Name','Department','Salary']]

       Name Department  Salary
0      Arun         IT   35000
1     Meera         HR   42000
2     Rahul    Finance   58000
3    Anjali         IT   39000
4    Vishnu      Sales   62000
5     Sneha         HR   45000
6   Adithya         IT   55000
7     Priya  Marketing   37000
8    Nikhil    Finance   72000
9   Fathima      Sales   48000
10    Kiran         IT   60000
11     Diya    Finance   68000
12    Rohan  Marketing   33000
13     Asha         HR   46000
14   Sanjay      Sales   65000

In [29]:
# A manager wants to see only:
# Name
# City
#Experience_Years
df5[['Name','City','Experience_Years']]

       Name       City  Experience_Years
0      Arun  Bangalore                 1
1     Meera      Kochi                 3
2     Rahul  Bangalore                 6
3    Anjali    Chennai                 2
4    Vishnu  Bangalore                 8
5     Sneha      Kochi                 4
6   Adithya  Hyderabad                 5
7     Priya  Bangalore                 1
8    Nikhil    Chennai                10
9   Fathima      Kochi                 3
10    Kiran  Bangalore                 7
11     Diya  Hyderabad                 9
12    Rohan      Kochi                 1
13     Asha    Chennai                 4
14   Sanjay  Bangalore                 8

In [30]:
# You need to create a smaller DataFrame containing:
# Employee_ID
# Name
# Age
# Salary
lista=[[1,'abi','22',2300]]
df6=pd.DataFrame(lista,columns=['Employee_ID','Name','Age','Salary'])
df6

   Employee_ID Name Age  Salary
0            1  abi  22    2300

In [31]:
df5[['Employee_ID','Name','Age','Salary']]

    Employee_ID     Name  Age  Salary
0           101     Arun   24   35000
1           102    Meera   29   42000
2           103    Rahul   32   58000
3           104   Anjali   26   39000
4           105   Vishnu   35   62000
5           106    Sneha   28   45000
6           107  Adithya   31   55000
7           108    Priya   25   37000
8           109   Nikhil   38   72000
9           110  Fathima   27   48000
10          111    Kiran   30   60000
11          112     Diya   34   68000
12          113    Rohan   23   33000
13          114     Asha   29   46000
14          115   Sanjay   36   65000

In [32]:
df5.loc[0]

Employee_ID                101
Name                      Arun
Age                         24
Department                  IT
Salary                   35000
City                 Bangalore
Experience_Years             1
Performance_Score           78
Name: 0, dtype: object

# row wise

In [33]:
df5.head()

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
4,105,Vishnu,35,Sales,62000,Bangalore,8,88

In [34]:
# loc[]---> gives row wise details using index position.
df5.loc[0]

Employee_ID                101
Name                      Arun
Age                         24
Department                  IT
Salary                   35000
City                 Bangalore
Experience_Years             1
Performance_Score           78
Name: 0, dtype: object

In [35]:
# Select the row with index 5.
df5.loc[5]

Employee_ID            106
Name                 Sneha
Age                     28
Department              HR
Salary               45000
City                 Kochi
Experience_Years         4
Performance_Score       79
Name: 5, dtype: object

In [36]:
# Select rows with index 2 to 6 using loc[].
df5.loc[2:6]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94

In [37]:
# Select rows with index 8 to 12 using loc[].
df5.loc[8:12]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
8,109,Nikhil,38,Finance,72000,Chennai,10,90
9,110,Fathima,27,Sales,48000,Kochi,3,84
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
12,113,Rohan,23,Marketing,33000,Kochi,1,75

In [38]:
# Select the Name and Salary of the employee at index 3 using loc[].
df5.loc[3,['Name','Salary']]

Name      Anjali
Salary     39000
Name: 3, dtype: object

In [39]:
# Select the Name, Age, and City of employees at indexes 5 to 8 using loc[].
df5.loc[5:8,['Name','Age','City']]

      Name  Age       City
5    Sneha   28      Kochi
6  Adithya   31  Hyderabad
7    Priya   25  Bangalore
8   Nikhil   38    Chennai

In [40]:
# iloc[]---> gives row wise detials using integer position.

In [41]:
# Using iloc[], select the first row of df5.
df5.iloc[0]

Employee_ID                101
Name                      Arun
Age                         24
Department                  IT
Salary                   35000
City                 Bangalore
Experience_Years             1
Performance_Score           78
Name: 0, dtype: object

In [42]:
# Select the 3rd row of df5 using iloc[].
df5.iloc[2]

Employee_ID                103
Name                     Rahul
Age                         32
Department             Finance
Salary                   58000
City                 Bangalore
Experience_Years             6
Performance_Score           91
Name: 2, dtype: object

In [43]:
# Select the 5th row to 8th row using iloc[]
df5.iloc[4:8]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
7,108,Priya,25,Marketing,37000,Bangalore,1,76

In [44]:
#Select:2nd to 4th rows,Name and Salary columns
# With iloc[], columns must also be selected by integer position, not by column names.
df5.iloc[1:4,[1,4]]

     Name  Salary
1   Meera   42000
2   Rahul   58000
3  Anjali   39000

In [45]:
#Select:
#1st to 5th rows
#Name, Age, and City Using iloc[].
df5.iloc[0:5,[1,2,5]]

     Name  Age       City
0    Arun   24  Bangalore
1   Meera   29      Kochi
2   Rahul   32  Bangalore
3  Anjali   26    Chennai
4  Vishnu   35  Bangalore

# filtering

In [46]:
# Show all employees whose Age is greater than 30.
df5[df5['Age']>30]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
2,103,Rahul,32,Finance,58000,Bangalore,6,91
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
6,107,Adithya,31,IT,55000,Hyderabad,5,94
8,109,Nikhil,38,Finance,72000,Chennai,10,90
11,112,Diya,34,Finance,68000,Hyderabad,9,89
14,115,Sanjay,36,Sales,65000,Bangalore,8,93

In [47]:
# Show all employees whose Salary is greater than 50,000.
df5[df5['Salary']>50000]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
2,103,Rahul,32,Finance,58000,Bangalore,6,91
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
6,107,Adithya,31,IT,55000,Hyderabad,5,94
8,109,Nikhil,38,Finance,72000,Chennai,10,90
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
14,115,Sanjay,36,Sales,65000,Bangalore,8,93

In [48]:
# Show all employees who work in the IT department.
df5[df5['Department']=='IT']

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
3,104,Anjali,26,IT,39000,Chennai,2,82
6,107,Adithya,31,IT,55000,Hyderabad,5,94
10,111,Kiran,30,IT,60000,Bangalore,7,92

In [49]:
# Show all employees whose Age is less than 30.
df5[df5['Age'] <30]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
3,104,Anjali,26,IT,39000,Chennai,2,82
5,106,Sneha,28,HR,45000,Kochi,4,79
7,108,Priya,25,Marketing,37000,Bangalore,1,76
9,110,Fathima,27,Sales,48000,Kochi,3,84
12,113,Rohan,23,Marketing,33000,Kochi,1,75
13,114,Asha,29,HR,46000,Chennai,4,86

In [50]:
# Show all employees whose Salary is less than or equal to ₹40,000.
df5[df5['Salary'] <= 40000]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
3,104,Anjali,26,IT,39000,Chennai,2,82
7,108,Priya,25,Marketing,37000,Bangalore,1,76
12,113,Rohan,23,Marketing,33000,Kochi,1,75

In [51]:
# Show all employees whose Age is greater than 30 AND Salary is greater than ₹50,000.
df5[(df5['Age'] > 30) & (df5['Salary']>50000)]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
2,103,Rahul,32,Finance,58000,Bangalore,6,91
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
6,107,Adithya,31,IT,55000,Hyderabad,5,94
8,109,Nikhil,38,Finance,72000,Chennai,10,90
11,112,Diya,34,Finance,68000,Hyderabad,9,89
14,115,Sanjay,36,Sales,65000,Bangalore,8,93

In [52]:
# Question: Show all employees who are either in IT OR HR.
df5[(df5['Department']=='IT') | (df5['Department']=='HR')]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
3,104,Anjali,26,IT,39000,Chennai,2,82
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
10,111,Kiran,30,IT,60000,Bangalore,7,92
13,114,Asha,29,HR,46000,Chennai,4,86

In [53]:
# Show employees whose Age is between 25 and 35.
df5[(df5['Age'] >=25) & (df5['Age'] <= 35)]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
7,108,Priya,25,Marketing,37000,Bangalore,1,76
9,110,Fathima,27,Sales,48000,Kochi,3,84
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
13,114,Asha,29,HR,46000,Chennai,4,86

In [54]:
# Show employees whose Salary is between ₹40,000 and ₹60,000.
df5[(df5['Salary']>=40000) & (df5['Salary']<=60000)]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
9,110,Fathima,27,Sales,48000,Kochi,3,84
10,111,Kiran,30,IT,60000,Bangalore,7,92
13,114,Asha,29,HR,46000,Chennai,4,86

In [55]:
# isin()---> to check values is in the list.
# Show all employees who work in IT, HR, or Finance.
df5[df5['Department'].isin(['IT','HR','Finance'])]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
8,109,Nikhil,38,Finance,72000,Chennai,10,90
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
13,114,Asha,29,HR,46000,Chennai,4,86

# DATA CLEANING

In [56]:
# isnull()---> check missing values.
df5.isnull().sum()

Employee_ID          0
Name                 0
Age                  0
Department           0
Salary               0
City                 0
Experience_Years     0
Performance_Score    0
dtype: int64

In [57]:
# fillna()---> filling missing values with values.
# If the Age column has missing values, how would you fill them with 30?
df5['Age'].fillna(30)

0     24
1     29
2     32
3     26
4     35
5     28
6     31
7     25
8     38
9     27
10    30
11    34
12    23
13    29
14    36
Name: Age, dtype: int64

In [58]:
# dropna()---> Remove missing values.
df5.dropna()

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
7,108,Priya,25,Marketing,37000,Bangalore,1,76
8,109,Nikhil,38,Finance,72000,Chennai,10,90
9,110,Fathima,27,Sales,48000,Kochi,3,84
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
12,113,Rohan,23,Marketing,33000,Kochi,1,75
13,114,Asha,29,HR,46000,Chennai,4,86
14,115,Sanjay,36,Sales,65000,Bangalore,8,93

In [59]:
# drop_duplicates---> used to remove duplicate value.
df5.drop_duplicates()

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score
0,101,Arun,24,IT,35000,Bangalore,1,78
1,102,Meera,29,HR,42000,Kochi,3,85
2,103,Rahul,32,Finance,58000,Bangalore,6,91
3,104,Anjali,26,IT,39000,Chennai,2,82
4,105,Vishnu,35,Sales,62000,Bangalore,8,88
5,106,Sneha,28,HR,45000,Kochi,4,79
6,107,Adithya,31,IT,55000,Hyderabad,5,94
7,108,Priya,25,Marketing,37000,Bangalore,1,76
8,109,Nikhil,38,Finance,72000,Chennai,10,90
9,110,Fathima,27,Sales,48000,Kochi,3,84
10,111,Kiran,30,IT,60000,Bangalore,7,92
11,112,Diya,34,Finance,68000,Hyderabad,9,89
12,113,Rohan,23,Marketing,33000,Kochi,1,75
13,114,Asha,29,HR,46000,Chennai,4,86
14,115,Sanjay,36,Sales,65000,Bangalore,8,93

In [60]:
# replace() → replaces one value with another.
# Replace HR with Human Resources in the Department column.
df5['Department'].replace('HR','Human Resources ')

0                   IT
1     Human Resources
2              Finance
3                   IT
4                Sales
5     Human Resources
6                   IT
7            Marketing
8              Finance
9                Sales
10                  IT
11             Finance
12           Marketing
13    Human Resources
14               Sales
Name: Department, dtype: object

# DATA MANIPULATION

In [61]:
# Adding Columns
# Create a new column called Bonus and give every employee a bonus of ₹5,000.
df5['Bonus']='5000'
df5

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score,Bonus
0,101,Arun,24,IT,35000,Bangalore,1,78,5000
1,102,Meera,29,HR,42000,Kochi,3,85,5000
2,103,Rahul,32,Finance,58000,Bangalore,6,91,5000
3,104,Anjali,26,IT,39000,Chennai,2,82,5000
4,105,Vishnu,35,Sales,62000,Bangalore,8,88,5000
5,106,Sneha,28,HR,45000,Kochi,4,79,5000
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000
7,108,Priya,25,Marketing,37000,Bangalore,1,76,5000
8,109,Nikhil,38,Finance,72000,Chennai,10,90,5000
9,110,Fathima,27,Sales,48000,Kochi,3,84,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000
11,112,Diya,34,Finance,68000,Hyderabad,9,89,5000
12,113,Rohan,23,Marketing,33000,Kochi,1,75,5000
13,114,Asha,29,HR,46000,Chennai,4,86,5000
14,115,Sanjay,36,Sales,65000,Bangalore,8,93,5000

In [62]:
# Create a new column called Total_Salary = Salary + Bonus
df5['Total_Salary']=(df5['Salary']+ df5['Bonus'])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
df5.dtypes

In [ ]:
# so covert bonus to numeric
df5['Bonus']=pd.to_numeric(df5['Bonus'])
df5.dtypes

In [ ]:
df5['Total_Salary']=df5['Salary']+df5['Bonus']
df5

In [ ]:
# Removing a Column
# Remove the Bonus column from df5.
df5.drop(columns='Bonus')

In [ ]:
# Renaming a column.
# Rename the column Salary to Annual_Salary.
df5.rename(columns={'Salary':'Annual_Salary'})

In [63]:
# sorting
# Sort employees by Salary from lowest to highest.
df5.sort_values(by='Salary')

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score,Bonus
12,113,Rohan,23,Marketing,33000,Kochi,1,75,5000
0,101,Arun,24,IT,35000,Bangalore,1,78,5000
7,108,Priya,25,Marketing,37000,Bangalore,1,76,5000
3,104,Anjali,26,IT,39000,Chennai,2,82,5000
1,102,Meera,29,HR,42000,Kochi,3,85,5000
5,106,Sneha,28,HR,45000,Kochi,4,79,5000
13,114,Asha,29,HR,46000,Chennai,4,86,5000
9,110,Fathima,27,Sales,48000,Kochi,3,84,5000
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000
2,103,Rahul,32,Finance,58000,Bangalore,6,91,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000
4,105,Vishnu,35,Sales,62000,Bangalore,8,88,5000
14,115,Sanjay,36,Sales,65000,Bangalore,8,93,5000
11,112,Diya,34,Finance,68000,Hyderabad,9,89,5000
8,109,Nikhil,38,Finance,72000,Chennai,10,90,5000

In [64]:
# Sort employees by Age from highest to lowest.
df5.sort_values(by='Age',ascending=False)

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score,Bonus
8,109,Nikhil,38,Finance,72000,Chennai,10,90,5000
14,115,Sanjay,36,Sales,65000,Bangalore,8,93,5000
4,105,Vishnu,35,Sales,62000,Bangalore,8,88,5000
11,112,Diya,34,Finance,68000,Hyderabad,9,89,5000
2,103,Rahul,32,Finance,58000,Bangalore,6,91,5000
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000
13,114,Asha,29,HR,46000,Chennai,4,86,5000
1,102,Meera,29,HR,42000,Kochi,3,85,5000
5,106,Sneha,28,HR,45000,Kochi,4,79,5000
9,110,Fathima,27,Sales,48000,Kochi,3,84,5000
3,104,Anjali,26,IT,39000,Chennai,2,82,5000
7,108,Priya,25,Marketing,37000,Bangalore,1,76,5000
0,101,Arun,24,IT,35000,Bangalore,1,78,5000
12,113,Rohan,23,Marketing,33000,Kochi,1,75,5000

In [65]:
# concat()---> used to combine 2 or more dataframe

In [66]:
employee1 = {
    'Name': ['Arun', 'Meera', 'Rahul'],
    'Age': [24, 29, 32],
    'Department': ['IT', 'HR', 'Finance']
}

employee2 = {
    'Name': ['Anjali', 'Vishnu', 'Sneha'],
    'Age': [26, 35, 28],
    'Department': ['IT', 'Sales', 'HR']
}

In [67]:
dfa=pd.DataFrame(employee1)
dfa

    Name  Age Department
0   Arun   24         IT
1  Meera   29         HR
2  Rahul   32    Finance

In [68]:
dfb=pd.DataFrame(employee2)
dfb

     Name  Age Department
0  Anjali   26         IT
1  Vishnu   35      Sales
2   Sneha   28         HR

In [69]:
# in pandas row---> axis=0
#            column-> axis=1
# Combine dfa and dfb row-wise.
pd.concat([dfa,dfb],axis=0)

     Name  Age Department
0    Arun   24         IT
1   Meera   29         HR
2   Rahul   32    Finance
0  Anjali   26         IT
1  Vishnu   35      Sales
2   Sneha   28         HR

In [70]:
# Combine dfa and dfb side by side (column-wise).
pd.concat([dfa,dfb],axis=1)

    Name  Age Department    Name  Age Department
0   Arun   24         IT  Anjali   26         IT
1  Meera   29         HR  Vishnu   35      Sales
2  Rahul   32    Finance   Sneha   28         HR

In [71]:
# Combine dfa and dfb row-wise and reset the index.
pd.concat([dfa,dfb],axis=0,ignore_index=True)

     Name  Age Department
0    Arun   24         IT
1   Meera   29         HR
2   Rahul   32    Finance
3  Anjali   26         IT
4  Vishnu   35      Sales
5   Sneha   28         HR

In [72]:
# groupby()---> groups data based on a column.
# Find the total salary for each department.
df5.groupby('Department')['Salary'].sum()

Department
Finance      198000
HR           133000
IT           189000
Marketing     70000
Sales        175000
Name: Salary, dtype: int64

In [73]:
# Find the average salary for each department.
df5.groupby('Department')['Salary'].sum()

Department
Finance      198000
HR           133000
IT           189000
Marketing     70000
Sales        175000
Name: Salary, dtype: int64

In [74]:
# Find the number of employees in each department.
df5.groupby('Department')['Salary'].count()

Department
Finance      3
HR           3
IT           4
Marketing    2
Sales        3
Name: Salary, dtype: int64

In [75]:
# Find the lowest salary in each department.
df5.groupby('Department')['Salary'].min()

Department
Finance      58000
HR           42000
IT           35000
Marketing    33000
Sales        48000
Name: Salary, dtype: int64

In [76]:
# Find the highest salary in each department.
df5.groupby('Department')['Salary'].max()

Department
Finance      72000
HR           46000
IT           60000
Marketing    37000
Sales        65000
Name: Salary, dtype: int64

In [77]:
# Find the total, average, minimum,maximum ,count salary for each department.
df5.groupby('Department')['Salary'].agg(['sum','mean','min','max','count'])

               sum          mean    min    max  count
Department
Finance     198000  66000.000000  58000  72000      3
HR          133000  44333.333333  42000  46000      3
IT          189000  47250.000000  35000  60000      4
Marketing    70000  35000.000000  33000  37000      2
Sales       175000  58333.333333  48000  65000      3

In [78]:
# pivot_table()---> create a summary table like excel pivot table.
# The average salary for each Department, separated by City. create a pivot table
df5.pivot_table(index='Department',columns='City',values='Salary',aggfunc='mean')

City        Bangalore  Chennai  Hyderabad    Kochi
Department
Finance       58000.0  72000.0    68000.0      NaN
HR                NaN  46000.0        NaN  43500.0
IT            47500.0  39000.0    55000.0      NaN
Marketing     37000.0      NaN        NaN  33000.0
Sales         63500.0      NaN        NaN  48000.0

In [79]:
#Create a pivot table showing the maximum Performance_Score for each Department, separated by City.
df5.pivot_table(index='Department',columns='City',values='Performance_Score',aggfunc='max')

City        Bangalore  Chennai  Hyderabad  Kochi
Department
Finance          91.0     90.0       89.0    NaN
HR                NaN     86.0        NaN   85.0
IT               92.0     82.0       94.0    NaN
Marketing        76.0      NaN        NaN   75.0
Sales            93.0      NaN        NaN   84.0

In [80]:
# Create a pivot table showing the total Salary for each Department, separated by City.
df5.pivot_table(index='Department',columns='City',values='Salary',aggfunc='sum')

City        Bangalore  Chennai  Hyderabad    Kochi
Department
Finance       58000.0  72000.0    68000.0      NaN
HR                NaN  46000.0        NaN  87000.0
IT            95000.0  39000.0    55000.0      NaN
Marketing     37000.0      NaN        NaN  33000.0
Sales        127000.0      NaN        NaN  48000.0

In [81]:
# crosstab()---> create frequency/count table between categorical column.
# Create a crosstab showing the number of employees in each Department, separated by City, and include the Total.
pd.crosstab(
    index=df5['Department'],
    columns=df5['City'],
    margins=True,
    margins_name='Total'
)

City        Bangalore  Chennai  Hyderabad  Kochi  Total
Department
Finance             1        1          1      0      3
HR                  0        1          0      2      3
IT                  2        1          1      0      4
Marketing           1        0          0      1      2
Sales               2        0          0      1      3
Total               6        3          2      4     15

In [82]:
# Using df5, create a crosstab that shows the number of employees in each City based on their Department, and include a Total row and column.
pd.crosstab(index=df5['Department'],
            columns=df5['City'],
            margins=True,
            margins_name='Total')

City        Bangalore  Chennai  Hyderabad  Kochi  Total
Department
Finance             1        1          1      0      3
HR                  0        1          0      2      3
IT                  2        1          1      0      4
Marketing           1        0          0      1      2
Sales               2        0          0      1      3
Total               6        3          2      4     15

In [83]:
# Create a crosstab showing the number of employees in each City based on their Performance Score.
pd.crosstab(index=df5['Performance_Score'],
            columns=df5['City'])

City               Bangalore  Chennai  Hyderabad  Kochi
Performance_Score
75                         0        0          0      1
76                         1        0          0      0
78                         1        0          0      0
79                         0        0          0      1
82                         0        1          0      0
84                         0        0          0      1
85                         0        0          0      1
86                         0        1          0      0
88                         1        0          0      0
89                         0        0          1      0
90                         0        1          0      0
91                         1        0          0      0
92                         1        0          0      0
93                         1        0          0      0
94                         0        0          1      0

In [84]:
# Create a crosstab showing the number of employees in each Department based on their Experience_Years.
pd.crosstab(index=df5['Experience_Years'],
            columns=df5['Department'])

Department        Finance  HR  IT  Marketing  Sales
Experience_Years
1                       0   0   1          2      0
2                       0   0   1          0      0
3                       0   1   0          0      1
4                       0   2   0          0      0
5                       0   0   1          0      0
6                       1   0   0          0      0
7                       0   0   1          0      0
8                       0   0   0          0      2
9                       1   0   0          0      0
10                      1   0   0          0      0

In [85]:
# value_counts()---> used to count values.
# Using df5, find how many employees are in each City.
df5['City'].value_counts()

City
Bangalore    6
Kochi        4
Chennai      3
Hyderabad    2
Name: count, dtype: int64

In [86]:
# unique()---> show unique values.
# Find all the different cities in df5.
df5['City'].unique()

array(['Bangalore', 'Kochi', 'Chennai', 'Hyderabad'], dtype=object)

In [87]:
# nunique---> used to give unique value counts.
# Find the number of different departments in df5.
df5['Department'].nunique()

5

In [88]:
df6=df5.copy()

In [89]:
# merge()---> used to combine 2 dataframe using common column.
# Merge df1 and df2 using Employee_ID and keep only matching employees.
pd.merge(df5,df6,on='Employee_ID',how='inner')

,Employee_ID,Name_x,Age_x,Department_x,Salary_x,City_x,Experience_Years_x,Performance_Score_x,Bonus_x,Name_y,Age_y,Department_y,Salary_y,City_y,Experience_Years_y,Performance_Score_y,Bonus_y
0,101,Arun,24,IT,35000,Bangalore,1,78,5000,Arun,24,IT,35000,Bangalore,1,78,5000
1,102,Meera,29,HR,42000,Kochi,3,85,5000,Meera,29,HR,42000,Kochi,3,85,5000
2,103,Rahul,32,Finance,58000,Bangalore,6,91,5000,Rahul,32,Finance,58000,Bangalore,6,91,5000
3,104,Anjali,26,IT,39000,Chennai,2,82,5000,Anjali,26,IT,39000,Chennai,2,82,5000
4,105,Vishnu,35,Sales,62000,Bangalore,8,88,5000,Vishnu,35,Sales,62000,Bangalore,8,88,5000
5,106,Sneha,28,HR,45000,Kochi,4,79,5000,Sneha,28,HR,45000,Kochi,4,79,5000
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000,Adithya,31,IT,55000,Hyderabad,5,94,5000
7,108,Priya,25,Marketing,37000,Bangalore,1,76,5000,Priya,25,Marketing,37000,Bangalore,1,76,5000
8,109,Nikhil,38,Finance,72000,Chennai,10,90,5000,Nikhil,38,Finance,72000,Chennai,10,90,5000
9,110,Fathima,27,Sales,48000,Kochi,3,84,5000,Fathima,27,Sales,48000,Kochi,3,84,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000,Kiran,30,IT,60000,Bangalore,7,92,5000
11,112,Diya,34,Finance,68000,Hyderabad,9,89,5000,Diya,34,Finance,68000,Hyderabad,9,89,5000
12,113,Rohan,23,Marketing,33000,Kochi,1,75,5000,Rohan,23,Marketing,33000,Kochi,1,75,5000
13,114,Asha,29,HR,46000,Chennai,4,86,5000,Asha,29,HR,46000,Chennai,4,86,5000
14,115,Sanjay,36,Sales,65000,Bangalore,8,93,5000,Sanjay,36,Sales,65000,Bangalore,8,93,5000

In [90]:
df5

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score,Bonus
0,101,Arun,24,IT,35000,Bangalore,1,78,5000
1,102,Meera,29,HR,42000,Kochi,3,85,5000
2,103,Rahul,32,Finance,58000,Bangalore,6,91,5000
3,104,Anjali,26,IT,39000,Chennai,2,82,5000
4,105,Vishnu,35,Sales,62000,Bangalore,8,88,5000
5,106,Sneha,28,HR,45000,Kochi,4,79,5000
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000
7,108,Priya,25,Marketing,37000,Bangalore,1,76,5000
8,109,Nikhil,38,Finance,72000,Chennai,10,90,5000
9,110,Fathima,27,Sales,48000,Kochi,3,84,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000
11,112,Diya,34,Finance,68000,Hyderabad,9,89,5000
12,113,Rohan,23,Marketing,33000,Kochi,1,75,5000
13,114,Asha,29,HR,46000,Chennai,4,86,5000
14,115,Sanjay,36,Sales,65000,Bangalore,8,93,5000

In [91]:
#join()---> combines two dataframe using index
df7= df5[['Name', 'Salary']]
df8 = df6[['Department', 'City']]
df7.join(df8)

       Name  Salary Department       City
0      Arun   35000         IT  Bangalore
1     Meera   42000         HR      Kochi
2     Rahul   58000    Finance  Bangalore
3    Anjali   39000         IT    Chennai
4    Vishnu   62000      Sales  Bangalore
5     Sneha   45000         HR      Kochi
6   Adithya   55000         IT  Hyderabad
7     Priya   37000  Marketing  Bangalore
8    Nikhil   72000    Finance    Chennai
9   Fathima   48000      Sales      Kochi
10    Kiran   60000         IT  Bangalore
11     Diya   68000    Finance  Hyderabad
12    Rohan   33000  Marketing      Kochi
13     Asha   46000         HR    Chennai
14   Sanjay   65000      Sales  Bangalore

In [92]:
df5[['Name','Salary']]

       Name  Salary
0      Arun   35000
1     Meera   42000
2     Rahul   58000
3    Anjali   39000
4    Vishnu   62000
5     Sneha   45000
6   Adithya   55000
7     Priya   37000
8    Nikhil   72000
9   Fathima   48000
10    Kiran   60000
11     Diya   68000
12    Rohan   33000
13     Asha   46000
14   Sanjay   65000

In [93]:
df5[df5['Salary']>50000]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score,Bonus
2,103,Rahul,32,Finance,58000,Bangalore,6,91,5000
4,105,Vishnu,35,Sales,62000,Bangalore,8,88,5000
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000
8,109,Nikhil,38,Finance,72000,Chennai,10,90,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000
11,112,Diya,34,Finance,68000,Hyderabad,9,89,5000
14,115,Sanjay,36,Sales,65000,Bangalore,8,93,5000

In [94]:
df5[(df5['Department']=='IT') & (df5['Salary']>50000)]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score,Bonus
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000

In [95]:
df5[df5['Department'].isin(['IT','HR','Finance'])]

,Employee_ID,Name,Age,Department,Salary,City,Experience_Years,Performance_Score,Bonus
0,101,Arun,24,IT,35000,Bangalore,1,78,5000
1,102,Meera,29,HR,42000,Kochi,3,85,5000
2,103,Rahul,32,Finance,58000,Bangalore,6,91,5000
3,104,Anjali,26,IT,39000,Chennai,2,82,5000
5,106,Sneha,28,HR,45000,Kochi,4,79,5000
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000
8,109,Nikhil,38,Finance,72000,Chennai,10,90,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000
11,112,Diya,34,Finance,68000,Hyderabad,9,89,5000
13,114,Asha,29,HR,46000,Chennai,4,86,5000

In [96]:
df5.groupby('Department')['Salary'].sum()

Department
Finance      198000
HR           133000
IT           189000
Marketing     70000
Sales        175000
Name: Salary, dtype: int64

In [97]:
df5.groupby('Department')['Salary'].max()

Department
Finance      72000
HR           46000
IT           60000
Marketing    37000
Sales        65000
Name: Salary, dtype: int64

In [98]:
df5.groupby('Department')['Salary'].count()

Department
Finance      3
HR           3
IT           4
Marketing    2
Sales        3
Name: Salary, dtype: int64

In [99]:
df5.groupby('Department')['Salary'].mean()

Department
Finance      66000.000000
HR           44333.333333
IT           47250.000000
Marketing    35000.000000
Sales        58333.333333
Name: Salary, dtype: float64

In [100]:
df5.pivot_table(index='Department',columns='City',values='Salary',aggfunc='mean')

City        Bangalore  Chennai  Hyderabad    Kochi
Department
Finance       58000.0  72000.0    68000.0      NaN
HR                NaN  46000.0        NaN  43500.0
IT            47500.0  39000.0    55000.0      NaN
Marketing     37000.0      NaN        NaN  33000.0
Sales         63500.0      NaN        NaN  48000.0

In [102]:
pd.crosstab(index=df5['Department'],
            columns=df5['City'],
            margins=True,
            margins_name='Total')

City        Bangalore  Chennai  Hyderabad  Kochi  Total
Department
Finance             1        1          1      0      3
HR                  0        1          0      2      3
IT                  2        1          1      0      4
Marketing           1        0          0      1      2
Sales               2        0          0      1      3
Total               6        3          2      4     15

In [109]:
df5['Department'].replace('HR','Human Resorce')

0                IT
1     Human Resorce
2           Finance
3                IT
4             Sales
5     Human Resorce
6                IT
7         Marketing
8           Finance
9             Sales
10               IT
11          Finance
12        Marketing
13    Human Resorce
14            Sales
Name: Department, dtype: object

In [110]:
df5.rename(columns={'Salary':'Annual_Salary'})

,Employee_ID,Name,Age,Department,Annual_Salary,City,Experience_Years,Performance_Score,Bonus
0,101,Arun,24,IT,35000,Bangalore,1,78,5000
1,102,Meera,29,HR,42000,Kochi,3,85,5000
2,103,Rahul,32,Finance,58000,Bangalore,6,91,5000
3,104,Anjali,26,IT,39000,Chennai,2,82,5000
4,105,Vishnu,35,Sales,62000,Bangalore,8,88,5000
5,106,Sneha,28,HR,45000,Kochi,4,79,5000
6,107,Adithya,31,IT,55000,Hyderabad,5,94,5000
7,108,Priya,25,Marketing,37000,Bangalore,1,76,5000
8,109,Nikhil,38,Finance,72000,Chennai,10,90,5000
9,110,Fathima,27,Sales,48000,Kochi,3,84,5000
10,111,Kiran,30,IT,60000,Bangalore,7,92,5000
11,112,Diya,34,Finance,68000,Hyderabad,9,89,5000
12,113,Rohan,23,Marketing,33000,Kochi,1,75,5000
13,114,Asha,29,HR,46000,Chennai,4,86,5000
14,115,Sanjay,36,Sales,65000,Bangalore,8,93,5000

In [111]:
df6 = df5[['Employee_ID', 'Name']]
df7 = df5[['Employee_ID', 'Salary']]
pd.merge(df6,df7,on='Employee_ID',how='inner')

    Employee_ID     Name  Salary
0           101     Arun   35000
1           102    Meera   42000
2           103    Rahul   58000
3           104   Anjali   39000
4           105   Vishnu   62000
5           106    Sneha   45000
6           107  Adithya   55000
7           108    Priya   37000
8           109   Nikhil   72000
9           110  Fathima   48000
10          111    Kiran   60000
11          112     Diya   68000
12          113    Rohan   33000
13          114     Asha   46000
14          115   Sanjay   65000

In [112]:
df7 = df5[['Name', 'Salary']]
df8 = df5[['Department', 'City']]
df7.join(df8)

       Name  Salary Department       City
0      Arun   35000         IT  Bangalore
1     Meera   42000         HR      Kochi
2     Rahul   58000    Finance  Bangalore
3    Anjali   39000         IT    Chennai
4    Vishnu   62000      Sales  Bangalore
5     Sneha   45000         HR      Kochi
6   Adithya   55000         IT  Hyderabad
7     Priya   37000  Marketing  Bangalore
8    Nikhil   72000    Finance    Chennai
9   Fathima   48000      Sales      Kochi
10    Kiran   60000         IT  Bangalore
11     Diya   68000    Finance  Hyderabad
12    Rohan   33000  Marketing      Kochi
13     Asha   46000         HR    Chennai
14   Sanjay   65000      Sales  Bangalore